language: cpp

compiler: g++

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq gcc-4.8 g++-4.8
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
  - cd test && g++ -std=c++11 -Wall test_timer.cc -o test_timer -lpthread -Wl,--no-as-needed

script:
  - ./runtest.sh

os:
  - linux
